### ISSUE TITLE
How to import data with references

### ISSUE THREAD

**Issue by abhirocks550** [contentstack/contentstack-import#24]
How can I insert entries with references?

Let's say I have Content type Home and I have one field which is logo which is
Image asset and other one is reference from other content type.

I am able to export the entries but when I am trying to import I could only 
Import textual data, not the image asset as well as the reference.

Can someone please help?

**Comment by rohitmishra209** [comment]
Hi Abhi,
I thing you are missing assets to import before content types and entries.
Before Content Types and Entries module import, we have to import assets module in stack.

For more questions raise a ticket to our help desk
